{"time":"2024-12-16T22:21:56.6634848+01:00","level":"INFO","msg":"using version","core version":"0.19.1"}
{"time":"2024-12-16T22:21:56.6644857+01:00","level":"INFO","msg":"created symlink","path":"c:\\Users\\ASUS\\Desktop\\PRIM\\src\\data\\wandb\\run-20241216_222156-ce1r7fhv\\logs\\debug-core.log"}
{"time":"2024-12-16T22:21:57.29997+01:00","level":"INFO","msg":"created new stream","id":"ce1r7fhv"}
{"time":"2024-12-16T22:21:57.29997+01:00","level":"INFO","msg":"stream: started","id":"ce1r7fhv"}
{"time":"2024-12-16T22:21:57.29997+01:00","level":"INFO","msg":"writer: Do: started","stream_id":"ce1r7fhv"}
{"time":"2024-12-16T22:21:57.29997+01:00","level":"INFO","msg":"sender: started","stream_id":"ce1r7fhv"}
{"time":"2024-12-16T22:21:57.29997+01:00","level":"INFO","msg":"handler: started","stream_id":"ce1r7fhv"}
{"time":"2024-12-16T22:21:57.5675858+01:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2024-12-16T23:45:35.2543135+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 10.30.118.10:52685->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-12-17T02:29:16.393266+01:00","level":"INFO","msg":"Pausing system monitor"}
